# Sample config
---
window:
  title: "Snake"
  background-color: 0x2596be
  width: 640
  height: 480
  fullscreen: false
  resizeable: true

textures:
  goose:
    filename: "assets/sprites/goose.png"
  apple:
    filename: "assets/sprites/Apple.png"
  gui_skin:
    filename: "assets/sprites/gui.png"

fonts:
  regular:
    filename: "assets/fonts/MartianMono-Regular.ttf"
    size: 32
    outline_size: 4
  bold:
    filename: "assets/fonts/MartianMono-Bold.ttf"
    size: 32

sprite_maps:
  apple_default:
    texture: "apple"
    x: 0
    y: 0
    w: 32
    h: 32
    n: 17
    fps: 20
  cross:
    texture: "gui_skin"
    x: 425
    y: 5
    w: 64
    h: 64

stretchables:
  window:
    texture: "gui_skin"
    center: { x: 32, y: 32, w: 16, h: 16 }
    top_left: { x: 16, y: 16, w: 16, h: 16 }
    top: { x: 32, y: 16, w: 16, h: 16 }
    top_right: { x: 48, y: 16, w: 16, h: 16 }
    right: { x: 48, y: 32, w: 16, h: 16 }
    bottom_right: { x: 48, y: 48, w: 16, h: 16 }
    bottom: { x: 32, y: 48, w: 16, h: 16 }
    bottom_left: { x: 16, y: 48, w: 16, h: 16 }
    left: { x: 16, y: 32, w: 16, h: 16 }
  button:
    texture: "gui_skin"
    center: { x: 96, y: 32, w: 16, h: 16 }
    top_left: { x: 80, y: 16, w: 16, h: 16 }
    top: { x: 96, y: 16, w: 16, h: 16 }
    top_right: { x: 112, y: 16, w: 16, h: 16 }
    right: { x: 112, y: 32, w: 16, h: 16 }
    bottom_right: { x: 112, y: 48, w: 16, h: 16 }
    bottom: { x: 96, y: 48, w: 16, h: 16 }
    bottom_left: { x: 80, y: 48, w: 16, h: 16 }
    left: { x: 80, y: 32, w: 16, h: 16 }
  button_mouse_over:
    texture: "gui_skin"
    center: { x: 96, y: 96, w: 16, h: 16 }
    top_left: { x: 80, y: 80, w: 16, h: 16 }
    top: { x: 96, y: 80, w: 16, h: 16 }
    top_right: { x: 112, y: 80, w: 16, h: 16 }
    right: { x: 112, y: 96, w: 16, h: 16 }
    bottom_right: { x: 112, y: 112, w: 16, h: 16 }
    bottom: { x: 96, y: 112, w: 16, h: 16 }
    bottom_left: { x: 80, y: 112, w: 16, h: 16 }
    left: { x: 80, y: 96, w: 16, h: 16 }
  button_mouse_down:
    texture: "gui_skin"
    center: { x: 96, y: 160, w: 16, h: 16 }
    top_left: { x: 80, y: 144, w: 16, h: 16 }
    top: { x: 96, y: 144, w: 16, h: 16 }
    top_right: { x: 112, y: 144, w: 16, h: 16 }
    right: { x: 112, y: 160, w: 16, h: 16 }
    bottom_right: { x: 112, y: 176, w: 16, h: 16 }
    bottom: { x: 96, y: 176, w: 16, h: 16 }
    bottom_left: { x: 80, y: 176, w: 16, h: 16 }
    left: { x: 80, y: 160, w: 16, h: 16 }

skins:
  window:
    base: "window"
  button:
    base: "button"
    hover: "button_mouse_over"
    active: "button_mouse_down"
